French translations
cobrowseio/cobrowse-agent-ui pull request #5
Opened 2022-10-06 16:24 UTC by HGray384

added as per the spec given in Trello. I wanted to match the style of what was there for spanish, so I also added `const french = 'fr'`, hope that's ok. This has not been tested by me.

2022-10-10 12:42 UTC, dyon requested changes
I can't push new commits to your branch so would you mind doing these little changes for me @HGray384 please?

1. I forgot to mention that we should also include the French locale for the date library. This can be done by adding `import 'moment/locale/fr';` on line 5, just below `import 'moment/locale/es';`.
2. Please remove the single quotes from `'fr'` on line 34 :).

This is how it looks when loaded onto Genesys:
![image](https://user-images.githubusercontent.com/35929/194867057-c526902a-ce4e-4b01-91d9-c4aceccfb1b1.png)

The part relevant to this PR's changes is the content below the **Devices** and **History** tabs. The `Vu pour la dernière fois il y a 19 jours` string seems to be too long, I don't know if there's a shorter alternative in French to tell the same thing? This makes the button narrower which hides part of its text. Another alternative would be to make the text wrap onto the next line. @headlessme thoughts on this?

2022-10-10 13:18 UTC, snyderj commented
@HGray384 let's try and shorten that line if possible.

2022-10-11 08:39 UTC, HGray384 commented
@dyon small changes made!

2022-10-11 09:13 UTC, dyon approved these changes

2022-10-11 11:01 UTC, merged